(function () {
  var dict = {
    my: {
      "title": "Perkhidmatan IT Pulau Pinang — Server, CCTV, Kelas Komputer & AI",
      "nav-services": "Perkhidmatan",
      "nav-coverage": "Kawasan Liputan",
      "nav-contact": "Hubungi Kami",
      "nav-portal": "Log Masuk",
      "nav-gateway": "ATEGateway",
      "nav-quote": "Minta Sebut Harga",
      "hero-slogan": "PANTAS - PROFESSIONAL - DIPERCAYAI",
      "hero-title": "Rakan perkhidmatan IT anda di Pulau Pinang",
      "hero-lead": "Pemasangan server, rack server, WiFi dan CCTV, kabel rangkaian, komputer dan laptop, serta kelas komputer dan AI — dikendalikan secara profesional, di rumah atau di pejabat.",
      "hero-btn-services": "Lihat Perkhidmatan",
      "hero-btn-contact": "Hubungi Kami",
      "hero-note": "Tindak balas pantas | Harga telus | Perkhidmatan di Pulau Pinang",
      "services-title": "Perkhidmatan Kami",
      "svc-1": "Pemasangan Server, Rack Server, WiFi & CCTV",
      "svc-1-desc": "Pemasangan dan konfigurasi server, rack server, sistem CCTV, dan liputan WiFi untuk rumah dan pejabat.",
      "svc-2": "Pemasangan Kabel Rangkaian",
      "svc-2-desc": "Pemasangan kabel rangkaian di rumah dan pejabat dengan kemasan yang kemas dan sambungan yang stabil.",
      "svc-3": "Pemasangan Komputer & Laptop",
      "svc-3-desc": "Pemasangan dan penyediaan komputer dan laptop di rumah dan pejabat, termasuk pemasangan perisian dan persediaan awal.",
      "svc-4": "Kelas Asas Kecerdasan Buatan (AI)",
      "svc-4-desc": "Kelas asasi AI secara online atau bersemuka — belajar cara menggunakan alatan AI secara praktikal dan mudah.",
      "svc-5": "Kelas Asas Komputer",
      "svc-5-desc": "Kelas online atau bersemuka untuk asas komputer, daripada tahap permulaan hingga kemahiran harian.",
      "svc-6": "Dan Banyak Lagi Perkhidmatan",
      "svc-6-desc": "Perkhidmatan lain tersedia mengikut permintaan. Hubungi kami untuk maklumat lanjut.",
      "coverage-title": "Kawasan Liputan",
      "coverage-state": "Negeri Tersedia",
      "coverage-island": "Kawasan Tersedia (Dalam Pulau)",
      "coverage-mainland": "Kawasan Tersedia (Seberang Pulau)",
      "coverage-note": "Perkhidmatan bergantung kepada kawasan. Caj pengangkutan akan dikenakan, termasuk caj kawasan luar. Banyak lagi perkhidmatan tersedia.",
      "booking-title": "Temujanji",
      "booking-service": "Perkhidmatan",
      "booking-date": "Tarikh",
      "booking-time": "Masa",
      "booking-name": "Nama Penuh",
      "booking-phone": "No. Telefon",
      "booking-email": "E-mel",
      "booking-location": "Kawasan / Lokasi",
      "booking-notes": "Nota (pilihan)",
      "booking-image": "Gambar (pilihan) — untuk rujukan admin",
      "booking-image-hint": "Maksimum 10MB. Contoh: gambar peranti/kerosakan.",
      "booking-video": "Video (pilihan) — untuk rujukan admin",
      "booking-video-hint": "Maksimum 50MB. Contoh: video masalah yang berlaku.",
      "booking-btn": "Rekod Temujanji",
      "why-title": "Kenapa Pilih Kami",
      "why-1": "Tindak Balas Pantas",
      "why-1-desc": "Kami bertindak balas dengan cepat supaya peranti, rangkaian dan sistem anda kembali berfungsi tanpa masa menunggu yang lama.",
      "why-2": "Harga Telus & Berpatutan",
      "why-2-desc": "Tiada caj tersembunyi. Anda mengetahui kos sebelum sebarang kerja dimulakan.",
      "why-3": "Remote & On-Site",
      "why-3-desc": "Daripada pembaikan jauh yang pantas kepada pemasangan bersemuka penuh, kami mengikut jadual anda.",
      "contact-title": "Hubungi Kami",
      "contact-call": "Hubungi / WhatsApp",
      "contact-call-btn": "Hubungi Sekarang",
      "booking-slot-btn": "Tempah Slot",
      "contact-email": "E-mel",
      "contact-email-btn": "Hantar E-mel",
      "contact-linkedin": "LinkedIn",
      "contact-linkedin-desc": "Berhubung dengan kami di LinkedIn.",
      "contact-linkedin-btn": "Lihat Profil",
      "contact-area": "Kawasan Perkhidmatan",
      "contact-area-desc": "Perkhidmatan on-site tersedia di Pulau Pinang. Sokongan remote tersedia di mana-mana.",
      "footer-line": "Server & rack server | WiFi & CCTV | Kabel rangkaian | Komputer & laptop | Kelas komputer & AI",
      "footer-copy": "© 2026 Hak cipta terpelihara.",
      "loading-text": "Sila tunggu...",
      "api-title": "Dokumentasi API ATEGateway",
      "api-lead": "Gerbang API AI khusus oleh Akmal Taufik Enterprise.",
      "api-base-title": "Base URL Production",
      "api-model-title": "Model Semasa",
      "api-auth-title": "Pengesahan",
      "api-auth-h": "Cara Pengesahan Berfungsi",
      "api-auth-desc": "Setiap permintaan mesti menyertakan kunci API anda dalam header Authorization. Dapatkan kunci anda melalui proses akaun pelanggan ATE.",
      "api-endpoints-title": "Endpoint",
      "api-col-desc": "Keterangan",
      "api-models-desc": "Senaraikan model yang tersedia untuk kunci anda.",
      "api-chat-desc": "Hantar perbualan dan terima pelengkapan model.",
      "api-example-title": "Contoh Permintaan",
      "api-curl-title": "Contoh curl",
      "api-stream-note": "Penstriman disokong dengan menetapkan stream kepada true.",
      "api-quick-title": "Mula Pantas",
      "api-q1": "Dapatkan kunci API ATEGateway anda.",
      "api-q2": "Set header Authorization.",
      "api-q3": "Gunakan Base URL production.",
      "api-q4": "Hantar permintaan ke /chat/completions.",
      "api-q5": "Pantau penggunaan melalui portal pelanggan.",
      "api-needkey-title": "Perlukan Kunci API?",
      "api-needkey-desc": "Hubungi kami untuk mendapatkan kunci API ATEGateway anda.",
      "api-needkey-btn": "Hubungi Kami",
      "api-back": "← Kembali ke laman utama"
    },
    en: {
      "title": "IT Services Penang — Server, CCTV, Computer & AI Classes",
      "nav-services": "Services",
      "nav-coverage": "Coverage Area",
      "nav-contact": "Contact Us",
      "nav-portal": "Login Here",
      "nav-gateway": "ATEGateway",
      "nav-quote": "Get a Quote",
      "hero-slogan": "FAST - PROFESSIONAL - TRUSTED",
      "hero-title": "Your trusted IT services partner in Penang",
      "hero-lead": "Server, rack server, WiFi and CCTV installation, network cabling, computer and laptop setup, plus computer and AI classes — handled professionally, at home or at the office.",
      "hero-btn-services": "Explore Services",
      "hero-btn-contact": "Contact Us",
      "hero-note": "Fast response | Transparent pricing | Serving Penang",
      "services-title": "Our Services",
      "svc-1": "Server, Rack Server, WiFi & CCTV Installation",
      "svc-1-desc": "Installation and configuration of servers, server racks, CCTV systems, and WiFi coverage for homes and offices.",
      "svc-2": "Network Cabling Installation",
      "svc-2-desc": "Network cable installation for homes and offices with neat finishing and stable connections.",
      "svc-3": "Computer & Laptop Setup",
      "svc-3-desc": "Computer and laptop setup at home and in the office, including software installation and initial configuration.",
      "svc-4": "Artificial Intelligence (AI) Beginner Classes",
      "svc-4-desc": "Beginner AI classes online or in person — learn how to use AI tools practically and easily.",
      "svc-5": "Basic Computer Classes",
      "svc-5-desc": "Online or in-person classes covering computer basics, from beginner level to everyday skills.",
      "svc-6": "And Many More Services",
      "svc-6-desc": "More services available on request. Contact us for more information.",
      "coverage-title": "Coverage Area",
      "coverage-state": "State Available",
      "coverage-island": "Available Areas (Island)",
      "coverage-mainland": "Available Areas (Mainland)",
      "coverage-note": "Services depend on the area. Transport charges apply, including out-of-area charges. Many more services are available.",
      "booking-title": "Appointment",
      "booking-service": "Service",
      "booking-date": "Date",
      "booking-time": "Time",
      "booking-name": "Full Name",
      "booking-phone": "Phone Number",
      "booking-email": "Email",
      "booking-location": "Area / Location",
      "booking-notes": "Notes (optional)",
      "booking-image": "Image (optional) — for admin reference",
      "booking-image-hint": "Max 10MB. E.g. photo of the device/damage.",
      "booking-video": "Video (optional) — for admin reference",
      "booking-video-hint": "Max 50MB. E.g. video of the issue.",
      "booking-btn": "Set Appointment",
      "why-title": "Why Choose Us",
      "why-1": "Fast Response",
      "why-1-desc": "We respond quickly so your devices, networks, and systems are back up with minimal downtime.",
      "why-2": "Clear, Fair Pricing",
      "why-2-desc": "No hidden charges. You know the cost before any work begins.",
      "why-3": "Remote & On-Site",
      "why-3-desc": "From quick remote fixes to full on-site installations, we work around your schedule.",
      "contact-title": "Get In Touch",
      "contact-call": "Call / WhatsApp",
      "contact-call-btn": "Call Now",
      "booking-slot-btn": "Book a Slot",
      "contact-email": "Email",
      "contact-email-btn": "Send Email",
      "contact-linkedin": "LinkedIn",
      "contact-linkedin-desc": "Connect with us on LinkedIn.",
      "contact-linkedin-btn": "View Profile",
      "contact-area": "Service Area",
      "contact-area-desc": "On-site service available in Penang. Remote support available everywhere.",
      "footer-line": "Server & rack server | WiFi & CCTV | Network cabling | Computers & laptops | Computer & AI classes",
      "footer-copy": "© 2026 All rights reserved.",
      "loading-text": "Please wait...",
      "api-title": "ATEGateway API Documentation",
      "api-lead": "A dedicated AI API gateway by Akmal Taufik Enterprise.",
      "api-base-title": "Production Base URL",
      "api-model-title": "Current Model",
      "api-auth-title": "Authentication",
      "api-auth-h": "How Authentication Works",
      "api-auth-desc": "Every request must include your API key in the Authorization header. Obtain your key through the ATE customer account process.",
      "api-endpoints-title": "Endpoints",
      "api-col-desc": "Description",
      "api-models-desc": "List the models available to your key.",
      "api-chat-desc": "Send a conversation and receive a model completion.",
      "api-example-title": "Example Request",
      "api-curl-title": "curl Example",
      "api-stream-note": "Streaming is supported by setting stream to true.",
      "api-quick-title": "Quick Start",
      "api-q1": "Obtain your ATEGateway API key.",
      "api-q2": "Set the Authorization header.",
      "api-q3": "Use the production Base URL.",
      "api-q4": "Send requests to /chat/completions.",
      "api-q5": "Monitor usage through the customer portal.",
      "api-needkey-title": "Need an API key?",
      "api-needkey-desc": "Contact us to get your ATEGateway API key.",
      "api-needkey-btn": "Contact Us",
      "api-back": "← Back to main website"
    }
  };

  function setLang(lang) {
    localStorage.setItem("site_lang", lang);
    var t = dict[lang];
    document.querySelectorAll("[data-i18n]").forEach(function (el) {
      var key = el.getAttribute("data-i18n");
      if (t[key] != null) {
        el.textContent = t[key];
        if (el.hasAttribute("data-text")) el.setAttribute("data-text", t[key]);
      }
    });
    document.querySelectorAll(".lang-btn").forEach(function (btn) {
      btn.classList.toggle("active", btn.getAttribute("data-lang") === lang);
    });
    document.documentElement.lang = lang === "my" ? "ms" : "en";
  }

  var saved = localStorage.getItem("site_lang") || "my";
  document.querySelectorAll(".lang-btn").forEach(function (btn) {
    btn.addEventListener("click", function () {
      setLang(btn.getAttribute("data-lang"));
    });
  });
  setLang(saved);
})();
